# Generated by Django 4.1.2 on 2022-12-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Exemple : A1417",
                        max_length=5,
                        verbose_name="Code de l'expérience",
                    ),
                ),
                (
                    "group",
                    models.CharField(max_length=50, verbose_name="Groupe d'expérience"),
                ),
                (
                    "labels",
                    models.CharField(
                        help_text="sous format json ?",
                        max_length=500,
                        verbose_name="labels de l'expérience",
                    ),
                ),
                (
                    "recipe_log",
                    models.FileField(
                        upload_to="recipe_log",
                        verbose_name="Fichier Growth .log qui contient le récapitulatif des étapes",
                    ),
                ),
                (
                    "shutter_csv",
                    models.FileField(
                        upload_to="shutter_csv",
                        verbose_name="Fichier Growth .csv qui contient les données des shutters",
                    ),
                ),
                (
                    "recipe_layer_number_tdms",
                    models.FileField(
                        upload_to="recipe_layer_number_tdms",
                        verbose_name="Fichier 'Recipe Layer Number.tdms' faisant le lien entre les étapes et le temps des capteurs",
                    ),
                ),
                (
                    "curvature_tdms",
                    models.FileField(
                        upload_to="curvature_tdms",
                        verbose_name="Fichier 'Curvature.tdms' des données de courbure",
                    ),
                ),
                (
                    "roughness_tdms",
                    models.FileField(
                        upload_to="roughness_tdms",
                        verbose_name="Fichier 'Roughness.tdms' des données de ruguouosité",
                    ),
                ),
                (
                    "wafer_temperature_tdms",
                    models.FileField(
                        upload_to="wafer_temperature_tdms",
                        verbose_name="Fichier 'Wafer Temperature.tdms' des données de température du wafer",
                    ),
                ),
                (
                    "reflectivity_tdms",
                    models.FileField(
                        upload_to="reflectivity_tdms",
                        verbose_name="Fichier 'Reflectivity.tdms' des données de réflectivité",
                    ),
                ),
            ],
        ),
    ]
